### ISSUE TITLE
the latest 'BH' package (1.58) breaks serialization code in flowWorkspace

### ISSUE THREAD

**Issue by mikejiang** [RGLab/flowWorkspace#178]
`flowWorkspace` compiles fine with `BH-1.55`, but failed after upgrading to `BH-1.58`

```c++
boost_serialization/shared_ptr_helper.cpp:36:1: error: ‘shared_ptr_helper_base’ has not been declared
 shared_ptr_helper_base::append(const boost_132::shared_ptr<const void> & t){
 ^
boost_serialization/shared_ptr_helper.cpp: In function ‘void boost::serialization::append(const boost_132::shared_ptr<const void>&)’:
boost_serialization/shared_ptr_helper.cpp:37:16: error: ‘m_pointers_132’ was not declared in this scope
     if(NULL == m_pointers_132)
               ^
```

Apparently `BH 1.58` doesn't play well with `boost serialization` module.
Before I could track down the source of issue, I wonder if it is worth to consider dropping `boost serialization` from the package entirely. (to avoid the future potential library version discrepancy)

To deal with the old archive in `BS` format, we can either set up a separate `converter` package based on existing code or add a build flag to switch on `boost serialization` build (by requesting `BH1.55` explicitly) and by default it will not build with `BS` support. By this, we can save some package compiling time.

**Comment by gfinak** [comment]
I like the converter package idea. If it tries to read an old archive it
points the user to the converter package which does one thing, reads and
resaves the archive.

Greg Finak

**Comment by raphg** [comment]
I agree with @gfinak. The converter package would be nice.

**Comment by mikejiang** [comment]
It turned out that `boost serialization` of  `1.58` contains the staled source file `shared_ptr_helper.cpp`, which contains all sorts of classes and variables defined nowhere in the source tree. 
After exclude that file, the package builds without errors.

But we'd still like to phase out `boost serialization` module and I will create a separate issue for that.
